function choices = sd_data_GetGrommetChoices()

choices = { ...
    '#NFLPS', ...
    '#NFHPS',...
    '#NFWMS', ...
    '#NFDSO', ...
    '#NOND1', ...
    '#PMRK1', ...
    '#EBPAS', ...
    '#EECEH', ...
    '#DUMMY', ...
};


