function SD=sd_data_Create()

    SD=struct(...
              'Lambda',[],...
              'SrcPos',[],...
              'DetPos', [],...
              'DummyPos', [],...
              'nSrcs',0,...
              'nDets',0,...
              'nDummys',0,...
              'MeasList',[],...
              'SpringList',[],...
              'AnchorList',[],...
              'SrcMap',[]...
             );
