function choices = GetGrommetChoices()

choices = { ...
    'none', ...
    '#NIRX2', ...
    '#NFLPS', ...
    '#NFHPS',...
    '#NFWMS', ...
    '#NFDSO', ...
    '#NOND1', ...
    '#NOND2', ...
    '#NOND3', ...
    '#NN21A', ...
    '#NN21B', ...
    '#PMRK1', ...
    '#EBPAS', ...
    '#EECEH', ...
    '#ACHLD', ...
};

% get grommet types from GrommetTypes_Custom.cfg file
% if isdeployed()
%     filename = [getAppDir(), 'GrommetTypes_Custom.cfg'];
% else
%     filename = which('GrommetTypes_Custom.cfg');
% end

cfg = ConfigFileClass();
custom_choices = cfg.GetMultiValues('Grommet Types');

if ~isempty(custom_choices)
    choices = union(choices, custom_choices, 'stable');
end