function T = rotateMatrixZaxis(theta0)

theta = deg2rad(theta0);
T =  [...
      cos(theta) -sin(theta)  0      0; ...
      sin(theta)  cos(theta)  0      0; ...
         0         0          1      0; ...
         0         0          0      1 ...
     ];
 