function err = optode_anchor_tbl_ErrCheck(tbl_data,tbl_size,r,c,nopt)

err=1;
if nopt==0
    return;
end

val = tbl_data{r,c};

if isempty(val)
    ;
elseif c==1
    if ~isnumber(val)
        return;
    end
    
    if str2num(val)>nopt || str2num(val)<1
        return;
    end
    
    optidx=[];
    jj=1;
    for ii=1:size(tbl_data,1)
        if ~isempty(tbl_data{ii,1})
            optidx(jj)=str2num(tbl_data{ii,1});
            jj=jj+1;
        end
    end
    if length(find(optidx==str2num(val)))>1
        return;
    end
elseif c==2
    labels = lower(refpts_label());
    val = lower(val);
    if isempty(find(strcmp(val,labels)))        
        val = str2num(val);
        if isempty(val)
            return;
        end
        if size(val,1)~=1 || size(val,2)~=3
            return;
        end
    end   
end
err=0;




% -----------------------------------------
function labels=refpts_label()
global atlasViewer

if isfield(atlasViewer,'refpts')
    labels = atlasViewer.refpts.labels;
    return
end

labels = ...
{ ...
'Nz    ' ; ...
'Iz    ' ; ...
'RPA   ' ; ... 
'LPA   ' ; ...
'Ar    ' ; ... 
'Al    ' ; ...
'A2    ' ; ... 
'A1    ' ; ...
'Cz    ' ; ... 
'NFpz  ' ; ...
'Fpz   ' ; ...
'AFpz  ' ; ...
'AFz   ' ; ...
'AFFz  ' ; ...
'Fz    ' ; ...
'FFCz  ' ; ...
'FCz   ' ; ...
'FCCz  ' ; ...
'CCPz  ' ; ...
'CPz   ' ; ...
'CPPz  ' ; ...
'Pz    ' ; ...
'PPOz  ' ; ...
'POz   ' ; ...
'POOz  ' ; ...
'Oz    ' ; ...
'OIz   ' ; ...
'T9h   ' ; ...
'T7    ' ; ...
'T7h   ' ; ...
'C5    ' ; ...
'C5h   ' ; ...
'C3    ' ; ...
'C3h   ' ; ...
'C1    ' ; ...
'C1h   ' ; ...
'C2h   ' ; ...
'C2    ' ; ...
'C4h   ' ; ...
'C4    ' ; ...
'C6h   ' ; ...
'C6    ' ; ...
'T8h   ' ; ...
'T8    ' ; ...
'T10h  ' ; ...
'Fp1h  ' ; ...
'Fp1   ' ; ...
'AFp7  ' ; ...
'AF7   ' ; ...
'AFF7  ' ; ...
'F7    ' ; ...
'FFT7  ' ; ...
'FT7   ' ; ...
'FTT7  ' ; ...
'TTP7  ' ; ...
'TP7   ' ; ...
'TPP7  ' ; ...
'P7    ' ; ...
'PPO7  ' ; ...
'PO7   ' ; ...
'POO7  ' ; ...
'O1    ' ; ...
'O1h   ' ; ...
'Fp2h  ' ; ...
'Fp2   ' ; ...
'AFp8  ' ; ...
'AF8   ' ; ...
'AFF8  ' ; ...
'F8    ' ; ...
'FFT8  ' ; ...
'FT8   ' ; ...
'FTT8  ' ; ...
'TTP8  ' ; ...
'TP8   ' ; ...
'TPP8  ' ; ...
'P8    ' ; ...
'PPO8  ' ; ...
'PO8   ' ; ...
'POO8  ' ; ...
'O2    ' ; ...
'O2h   ' ; ...
'F7h   ' ; ...
'F5    ' ; ...
'F5h   ' ; ...
'F3    ' ; ...
'F3h   ' ; ...
'F1    ' ; ...
'F1h   ' ; ...
'F2h   ' ; ...
'F2    ' ; ...
'F4h   ' ; ...
'F4    ' ; ...
'F6h   ' ; ...
'F6    ' ; ...
'F8h   ' ; ...
'P7h   ' ; ...
'P5    ' ; ...
'P5h   ' ; ...
'P3    ' ; ...
'P3h   ' ; ...
'P1    ' ; ...
'P1h   ' ; ...
'P2h   ' ; ...
'P2    ' ; ...
'P4h   ' ; ...
'P4    ' ; ...
'P6h   ' ; ...
'P6    ' ; ...
'P8h   ' ; ...
'AF7h  ' ; ...
'AF5   ' ; ...
'AF5h  ' ; ...
'AF3   ' ; ...
'AF3h  ' ; ...
'AF1   ' ; ...
'AF1h  ' ; ...
'AF2h  ' ; ...
'AF2   ' ; ...
'AF4h  ' ; ...
'AF4   ' ; ...
'AF6h  ' ; ...
'AF6   ' ; ...
'AF8h  ' ; ...
'PO7h  ' ; ...
'PO5   ' ; ...
'PO5h  ' ; ...
'PO3   ' ; ...
'PO3h  ' ; ...
'PO1   ' ; ...
'PO1h  ' ; ...
'PO2h  ' ; ...
'PO2   ' ; ...
'PO4h  ' ; ...
'PO4   ' ; ...
'PO6h  ' ; ...
'PO6   ' ; ...
'PO8h  ' ; ...
'FT7h  ' ; ...
'FC5   ' ; ...
'FC5h  ' ; ...
'FC3   ' ; ...
'FC3h  ' ; ...
'FC1   ' ; ...
'FC1h  ' ; ...
'FC2h  ' ; ...
'FC2   ' ; ...
'FC4h  ' ; ...
'FC4   ' ; ...
'FC6h  ' ; ...
'FC6   ' ; ...
'FT8h  ' ; ...
'TP7h  ' ; ...
'CP5   ' ; ...
'CP5h  ' ; ...
'CP3   ' ; ...
'CP3h  ' ; ...
'CP1   ' ; ...
'CP1h  ' ; ...
'CP2h  ' ; ...
'CP2   ' ; ...
'CP4h  ' ; ...
'CP4   ' ; ...
'CP6h  ' ; ...
'CP6   ' ; ...
'TP8h  ' ; ...
'FTT7h ' ; ...
'FCC5  ' ; ...
'FCC5h ' ; ...
'FCC3  ' ; ...
'FCC3h ' ; ...
'FCC1  ' ; ...
'FCC1h ' ; ...
'FCC2h ' ; ...
'FCC2  ' ; ...
'FCC4h ' ; ...
'FCC4  ' ; ...
'FCC6h ' ; ...
'FCC6  ' ; ...
'FTT8h ' ; ...
'TTP7h ' ; ...
'CCP5  ' ; ...
'CCP5h ' ; ...
'CCP3  ' ; ...
'CCP3h ' ; ...
'CCP1  ' ; ...
'CCP1h ' ; ...
'CCP2h ' ; ...
'CCP2  ' ; ...
'CCP4h ' ; ...
'CCP4  ' ; ...
'CCP6h ' ; ...
'CCP6  ' ; ...
'TTP8h ' ; ...
'FFT7h ' ; ...
'FFC5  ' ; ...
'FFC5h ' ; ...
'FFC3  ' ; ...
'FFC3h ' ; ...
'FFC1  ' ; ...
'FFC1h ' ; ...
'FFC2h ' ; ...
'FFC2  ' ; ...
'FFC4h ' ; ...
'FFC4  ' ; ...
'FFC6h ' ; ...
'FFC6  ' ; ...
'FFT8h ' ; ...
'TPP7h ' ; ...
'CPP5  ' ; ...
'CPP5h ' ; ...
'CPP3  ' ; ...
'CPP3h ' ; ...
'CPP1  ' ; ...
'CPP1h ' ; ...
'CPP2h ' ; ...
'CPP2  ' ; ...
'CPP4h ' ; ...
'CPP4  ' ; ...
'CPP6h ' ; ...
'CPP6  ' ; ...
'TPP8h ' ; ...
'AFF7h ' ; ...
'AFF5  ' ; ...
'AFF5h ' ; ...
'AFF3  ' ; ...
'AFF3h ' ; ...
'AFF1  ' ; ...
'AFF1h ' ; ...
'AFF2h ' ; ...
'AFF2  ' ; ...
'AFF4h ' ; ...
'AFF4  ' ; ...
'AFF6h ' ; ...
'AFF6  ' ; ...
'AFF8h ' ; ...
'PPO7h ' ; ...
'PPO5  ' ; ...
'PPO5h ' ; ...
'PPO3  ' ; ...
'PPO3h ' ; ...
'PPO1  ' ; ...
'PPO1h ' ; ...
'PPO2h ' ; ...
'PPO2  ' ; ...
'PPO4h ' ; ...
'PPO4  ' ; ...
'PPO6h ' ; ...
'PPO6  ' ; ...
'PPO8h ' ; ...
'AFp5  ' ; ...
'AFp3  ' ; ...
'AFp1  ' ; ...
'AFp2  ' ; ...
'AFp4  ' ; ...
'AFp6  ' ; ...
'POO5  ' ; ...
'POO3  ' ; ...
'POO1  ' ; ...
'POO2  ' ; ...
'POO4  ' ; ...
'POO6  ' ; ...
'NFp1h ' ; ...
'NFp1  ' ; ...
'AFp9h ' ; ...
'AF9h  ' ; ...
'AFF9h ' ; ...
'F9h   ' ; ...
'FFT9h ' ; ...
'FT9h  ' ; ...
'FTT9h ' ; ...
'TTP9h ' ; ...
'TP9h  ' ; ...
'TPP9h ' ; ...
'P9h   ' ; ...
'PPO9h ' ; ...
'PO9h  ' ; ...
'POO9h ' ; ...
'OI1   ' ; ...
'OI1h  ' ; ...
'NFp2h ' ; ...
'NFp2  ' ; ...
'AFp10h' ; ...
'AF10h ' ; ...
'AFF10h' ; ...
'F10h  ' ; ...
'FFT10h' ; ...
'FT10h ' ; ...
'FTT10h' ; ...
'TTP10h' ; ...
'TP10h ' ; ...
'TPP10h' ; ...
'P10h  ' ; ...
'PPO10h' ; ...
'PO10h ' ; ...
'POO10h' ; ... 
'OI2   ' ; ...
'OI2h  '   ...
};

for ii=1:length(labels)
    k=findstr(' ',labels{ii});
    labels{ii}(k) = [];
end





% -----------------------------------------
function b = isnumber(str)  
b = ~isempty(str2num(str));

