function SD = sd_data_Init(SD0)

SD = struct(...
    'Lambda',[], ...
    'SrcPos',[], ...
    'DetPos',[], ...
    'DummyPos',[], ...
    'SrcPos3D',[], ...
    'DetPos3D',[], ...
    'DummyPos3D',[], ...
    'SrcGrommetType',{{}}, ...
    'DetGrommetType',{{}}, ...
    'DummyGrommetType',{{}}, ...
    'SrcGrommetRot',{{}}, ...
    'DetGrommetRot',{{}}, ...
    'DummyGrommetRot',{{}}, ...
    'nSrcs',0, ...
    'nDets',0, ...
    'nDummys',0, ...
    'Landmarks',sd_data_InitLandmarks(), ...
    'Landmarks2D',sd_data_InitLandmarks(), ...
    'MeasList',[], ...
    'MeasListAct',[], ...
    'SpringList',[], ...
    'AnchorList',[], ...
    'SrcMap',[], ...
    'SpatialUnit','', ...
    'xmin',0, ...
    'xmax',0, ...
    'ymin',0, ...
    'ymax',0, ...
    'auxChannels',[], ...
    'orientation','' ...
    );

if nargin==0
    return;
end

SD = sd_data_Copy(SD, SD0);

