function choices = sd_data_GetGrommetChoices()

% This is to make sure we update just one cfg file for grommet choices then SDgui and
% AtlasViewer can use same cfg file.
choices = GetGrommetChoices();
% choices = { ...
%     'none', ...
%     '#NIRX2', ...
%     '#NFLPS', ...
%     '#NFHPS',...
%     '#NFWMS', ...
%     '#NFDSO', ...
%     '#NOND1', ...
%     '#NOND2', ...
%     '#NOND3', ...
%     '#NN21A', ...
%     '#NN21B', ...
%     '#PMRK1', ...
%     '#EBPAS', ...
%     '#EECEH', ...
%     '#ACHLD', ...
% };


