function choices = sd_data_GetGrommetChoices()

choices = { ...
    'none', ...
    '#NIRX2', ...
    '#NFLPS', ...
    '#NFHPS',...
    '#NFWMS', ...
    '#NFDSO', ...
    '#NOND1', ...
    '#NOND2', ...
    '#PMRK1', ...
    '#EBPAS', ...
    '#EECEH', ...
    '#ACHLD', ...
};


